CREATE TABLE IF NOT EXISTS `ads` (
`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
`case_name` VARCHAR(16) NOT NULL DEFAULT '',
`url` VARCHAR(255) NOT NULL DEFAULT '',
`item_id` CHAR(32) NOT NULL DEFAULT '',
`phone` CHAR(16) NOT NULL DEFAULT '',
`name` VARCHAR(32) NOT NULL DEFAULT '',
`title` VARCHAR(32) NOT NULL DEFAULT '',
`service` VARCHAR(32) NOT NULL DEFAULT '',
`place` VARCHAR(32) NOT NULL DEFAULT '',
`description` VARCHAR(5120) NOT NULL DEFAULT '',
`price` VARCHAR(32) NOT NULL DEFAULT '',
`parse_status` INT(11) UNSIGNED NOT NULL DEFAULT 0,
PRIMARY KEY (`id`),
UNIQUE KEY `idx_case` (`case_name`, `url`)
) ENGINE = INNODB DEFAULT CHARSET=utf8;