CREATE TABLE IF NOT EXISTS `ads` (
`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
`case_name` VARCHAR(32) NOT NULL DEFAULT '',
`url` VARCHAR(512) NOT NULL DEFAULT '',
`item_id` CHAR(32) NOT NULL DEFAULT '',
`phone` CHAR(16) NOT NULL DEFAULT '',
`data_json` VARCHAR(10240) NOT NULL DEFAULT '',
`parse_status` INT(11) UNSIGNED NOT NULL DEFAULT 0,
PRIMARY KEY (`id`),
UNIQUE KEY `idx_case` (`case_name`, `url`)
) ENGINE = INNODB;